name: dHG
version: 1.0
author: dodocarlos
main: me.dhg.principal.Main
description: dHG
depend: [WorldEdit]
commands:
    iniciar:
    admin:
    tag:
    ffeast:
    feast:
    fmfeast:
    kit:
    spawn:
    settime:
    skit:
    fake:
    youtuber:
    info:
    check:
    teleport:
    cleardrops:
    dano:
    arena:
    ver:
    version:
    about:
    chat:
    bc:
    inv:
    specs:
    desistir:
    time:
    tpall:
    removerkits:
    ban:
    unban:
    ip:
    report:
    addgateblocks: